---
title: "APRW Comments"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Major Comments

-   Utility function designs have an assumption that past reform does not impact anything

-   Why not measure the greatest good for the greatest number as your focus

-   Why use New Jersey?
    (We should probably use Illinois. No party data for Missouri.)

    -   If we show NJ, we should include the enacted plan

-   Is Harm too strong a word?

    -   For general things, maybe?
    -   If we want to tie it to court-speak, they use harm and injury for this, so it fits.

-   Not 100% clear why the certain maps end up the ways that they do: unpack this

    -   Why might local maximizing not just be super packed (ie compactness and political geography)

        -   if this is a strength, use it!

-   Setting utility as 0 for nonvoters misses something.
    How might we compare voters vs eligible voters in a state?

    -   Use party registration

        -   if FL, then we get race, party, and turnout all in one

-   For framing the contribution, spend more time thinking about the harm and drop the global aspects

-   Can we consider more complex utility functions?

    -   Mix across types of utility
    -   Basic mixing of local and global (rather than pure)

-   Should think about how ideology matters

    -   Use a school district?
    -   Lean into a locality for a cleaner example where party is different

-   How does precinct heterogeneity map into this (Chris needs to work more on that party vs race presentation)

### Steve Comments

-   Drop the whole utility thing

-   lean into how it relates to existing voters

    -   If we weight by voters, do we recover some egap approximation or transformation?

-   Add in an aspect of racial mapping?

    -   include optimization over two dimension -- racial and partisan harm

        -   large 1990s-2000s literature on the costs and benefits of MMDs (Washington etc)

-   How does adding constraints to a simulation change the dimensions of harm?

    -   If we want tot htink about constraints more in how the law does, then spend more time on that
    -   Also consider if this is how *we* think about it

-   Ask: What does equal protection imply?

    -   If you start at equal protection, then you need to think about turnout
    -   That's where there's purchase to talk about differing turnout

-   The big open world for this is if we can get better understanding of what makes a district performant for racial party reasons

    -   Can we use this mechanism to create a threshold?
    -   Mix party with census race
    -   Race x candidate data and code from [Shiro via Jeremiah](https://wholeads.us/research/2020-ballot-demographics/)

## Presentation Comments

-   Make clearer the generalization to probabilities
-   Put the utility maximization together on the slides with the harm for the mini cases

## Paper Comments ()

-   Paper seems very motivated by the court emphasis on individual representation

    -   Seems like a strong approach to trying to understand the microfoundations of redistricting

-   Paper offers lots of measures but then seems to indicate that what we care about is fairness

    -   not totally clear why fairness is an *individual* measure (seems very party oriented)
    -   Can this be tied more clearly to individual harm?

-   Nonvoters and can't voters utility of 0

    -   Spend more time justifying this (is it standing?)
    -   How could we extend to asymmetric partisan preferences?

-   Rawls social welfare (??)

-   Expand more onto the idea that global considerations don't really matter for fairness

-   Does local utility best capture partisan cheerleaders

-   Expand to higher moments of harm

    -   Do we maybe sometimes care more about minimizing the change in harm as swings occur?

-   Spend more time discussing the actual interpretation of what the harm measure gives you

    -   Doesn't have the super clear % seats interpretation, so this seems very useful

-   Justify the use of `g() = log()`.

-   I wrote "systematicity" and underlined it from Jacob's discussion (why? I don't know.)

-   Is there room for some basic discussion of tiered preferences?

-   For discussing New Jersey, spend some time talking about the when/where/why/so what of the differences across measures?
    [less meaningful if we focus on partisan harm]
